[package]
name = "rspark"
version = "0.1.0"
authors = ["Thomas Harmon <thomas.alan.harmon@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sorer = { git = "https://github.com/SamedhG/sorer", branch = "rspark" }

